-- require('plugins/airline')
require('plugins/nvim-tree_tree')
require('plugins/bufferline_')
require('plugins/nvim-cmp')
require('plugins/nvim-treesitter')
require('plugins/telescope')
require('plugins/floaterm')
require('plugins/leetcode')
require('plugins/indentLine')
require('plugins/NERD_Commenter')
require('plugins/nvim-colorizer_lua')
require('plugins/bigfile')
-- require('plugins/nvim-notify')
require('plugins/tabout')
require('plugins/jupyter_nvim')
require('plugins/vim_slime')
require('plugins/rust-tools-config')
require('plugins/vimtex')

-- require('plugins/ipython_cell')
--require('plugins/nvim-lspconfig')
--require('plugins/neoformat')
