require('plugins/airline')
require('plugins/nvim-cmp')
require('plugins/nvim-treesitter')
require('plugins/telescope')
require('plugins/nvim-tree')
require('plugins/floaterm')
require('plugins/leetcode')
require('plugins/indentLine')
require('plugins/NERD_Commenter')
require('plugins/nvim-colorizer_lua')
require('plugins/bigfile')
require('plugins/nvim-notify')
require('plugins/tabout')
require('plugins/jupyter-nvim')
-- require('plugins/slime')
-- require('plugins/ipython-cell')
--require('plugins/nvim-lspconfig')
