require('plugins/airline')
require('plugins/nvim-lspconfig')
require('plugins/nvim-cmp')
require('plugins/nvim-treesitter')
require('plugins/telescope')
require('plugins/nvim-tree')
require('plugins/floaterm')
require('plugins/leetcode')
