require('plugins/nvim-cmp')
require('plugins/nvim-treesitter')
require('plugins/telescope')
require('plugins/floaterm')
require('plugins/leetcode')
require('plugins/indentLine')
require('plugins/comment_')
require('plugins/nvim-colorizer_lua')
require('plugins/bigfile')
require('plugins/tabout')
require('plugins/vim_slime')
require('plugins/rust-tools-config')
require('plugins/vimtex')
require('plugins/bufferline_')
require('plugins/gitsigns_')
require('plugins/comment_')
require('plugins/neo_tree_')
require('plugins/heirline_')
require('plugins/toggleterm_')
require('plugins/none_ls_')
require('plugins/trouble_')
require('plugins/mini_')
-- require('plugins/airline')
-- require('plugins/nvim-tree_tree')
-- require('plugins/NERD_Commenter')
-- require('plugins/nvim-notify')
-- require('plugins/jupyter_nvim')
-- require('plugins/nvim_windows_packer_')
-- require('plugins/ipython_cell')
--require('plugins/nvim-lspconfig')
--require('plugins/neoformat')
